name: Terminate BPF App

on:
  workflow_dispatch:

jobs:
  terminate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Decode PEM Key
      run: |
        echo "${{ secrets.AWS_PEM_BASE64 }}" | base64 -d > key.pem
        chmod 400 key.pem

    - name: Get Terraform Output (EC2 IP)
      id: get_ip
      run: |
        cd terraform
        echo "EC2_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

    - name: Kill Python Processes on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_IP << 'EOF'
          echo "Killing all running Python scripts..."
          pkill -f main.py || true
          pkill -f anomaly_detect.py || true
        EOF
